# Use the latest node alpine image
FROM node:26-alpine

# Set working directory
WORKDIR /app/frontend

# Install dependencies only when package files change
COPY package.json package-lock.json ./
RUN npm install

# Copy source code
COPY . .

# Expose Next.js port
EXPOSE 3000

# Start development mode
CMD ["npm", "run", "dev"]