// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type MuseumhubArtwork struct {
	ID              string             `json:"id"`
	Author          string             `json:"author"`
	Title           string             `json:"title"`
	Description     string             `json:"description"`
	Museum          string             `json:"museum"`
	ImageUrl        string             `json:"image_url"`
	ImagePreviewUrl string             `json:"image_preview_url"`
	Year            string             `json:"year"`
	Source          string             `json:"source"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type MuseumhubQuery struct {
	Query      string             `json:"query"`
	Count      int32              `json:"count"`
	LastUpdate pgtype.Timestamptz `json:"last_update"`
}
