// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
)

const getStaleQueries = `-- name: GetStaleQueries :many
SELECT query 
FROM museumhub.queries 
WHERE last_update < NOW() - INTERVAL '1 day'
ORDER BY last_update ASC 
LIMIT 1
`

func (q *Queries) GetStaleQueries(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getStaleQueries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var query string
		if err := rows.Scan(&query); err != nil {
			return nil, err
		}
		items = append(items, query)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchArtworks = `-- name: SearchArtworks :many
SELECT 
    id, author, title, description, museum, image_url, image_preview_url, year, source, created_at, updated_at
FROM 
    museumhub.artworks
WHERE 
    search_vector @@ websearch_to_tsquery('simple', $1::text)
ORDER BY 
    id
LIMIT $3::int
OFFSET $2::int
`

type SearchArtworksParams struct {
	SearchTerm string `json:"search_term"`
	PageOffset int32  `json:"page_offset"`
	PageLimit  int32  `json:"page_limit"`
}

func (q *Queries) SearchArtworks(ctx context.Context, arg SearchArtworksParams) ([]MuseumhubArtwork, error) {
	rows, err := q.db.Query(ctx, searchArtworks, arg.SearchTerm, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MuseumhubArtwork
	for rows.Next() {
		var i MuseumhubArtwork
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Title,
			&i.Description,
			&i.Museum,
			&i.ImageUrl,
			&i.ImagePreviewUrl,
			&i.Year,
			&i.Source,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertArtwork = `-- name: UpsertArtwork :one

INSERT INTO museumhub.artworks (
    id, 
    author, 
    title, 
    description, 
    museum, 
    image_url, 
    image_preview_url, 
    year, 
    source
) 
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO UPDATE SET
    author            = EXCLUDED.author,
    title             = EXCLUDED.title,
    description       = EXCLUDED.description,
    museum            = EXCLUDED.museum,
    image_url         = EXCLUDED.image_url,
    image_preview_url = EXCLUDED.image_preview_url,
    year              = EXCLUDED.year,
    source            = EXCLUDED.source
RETURNING id, author, title, description, museum, image_url, image_preview_url, year, source, created_at, updated_at
`

type UpsertArtworkParams struct {
	ID              string `json:"id"`
	Author          string `json:"author"`
	Title           string `json:"title"`
	Description     string `json:"description"`
	Museum          string `json:"museum"`
	ImageUrl        string `json:"image_url"`
	ImagePreviewUrl string `json:"image_preview_url"`
	Year            string `json:"year"`
	Source          string `json:"source"`
}

// ==========
// Museum Hub
// ==========
func (q *Queries) UpsertArtwork(ctx context.Context, arg UpsertArtworkParams) (MuseumhubArtwork, error) {
	row := q.db.QueryRow(ctx, upsertArtwork,
		arg.ID,
		arg.Author,
		arg.Title,
		arg.Description,
		arg.Museum,
		arg.ImageUrl,
		arg.ImagePreviewUrl,
		arg.Year,
		arg.Source,
	)
	var i MuseumhubArtwork
	err := row.Scan(
		&i.ID,
		&i.Author,
		&i.Title,
		&i.Description,
		&i.Museum,
		&i.ImageUrl,
		&i.ImagePreviewUrl,
		&i.Year,
		&i.Source,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertSearchQuery = `-- name: UpsertSearchQuery :one
INSERT INTO museumhub.queries (query, count)
VALUES ($1::text, 1)
ON CONFLICT (query) DO UPDATE SET
    count = museumhub.queries.count + 1
RETURNING query, count, last_update
`

func (q *Queries) UpsertSearchQuery(ctx context.Context, queryText string) (MuseumhubQuery, error) {
	row := q.db.QueryRow(ctx, upsertSearchQuery, queryText)
	var i MuseumhubQuery
	err := row.Scan(&i.Query, &i.Count, &i.LastUpdate)
	return i, err
}
