// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	GetStaleQueries(ctx context.Context) ([]string, error)
	SearchArtworks(ctx context.Context, arg SearchArtworksParams) ([]MuseumhubArtwork, error)
	// ==========
	// Museum Hub
	// ==========
	UpsertArtwork(ctx context.Context, arg UpsertArtworkParams) (MuseumhubArtwork, error)
	UpsertSearchQuery(ctx context.Context, queryText string) (MuseumhubQuery, error)
}

var _ Querier = (*Queries)(nil)
